sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true $DOCKER_USERNAME/react-test npm run test

after_success:
  - docker build -t $DOCKER_USERNAME/multi-client ./client
  - docker build -t $DOCKER_USERNAME/multi-nginx ./nginx
  - docker build -t $DOCKER_USERNAME/multi-server ./server
  - docker build -t $DOCKER_USERNAME/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take all images and push them to docker hub
  - docker push $DOCKER_USERNAME/multi-client
  - docker push $DOCKER_USERNAME/multi-nginx
  - docker push $DOCKER_USERNAME/multi-server
  - docker push $DOCKER_USERNAME/multi-worker
